service: psychic-waddle
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  emoji:
    handler: bin/emoji
    events:
      - httpApi:
          path: /emoji
          method: get
    environment:
      SOURCE_URL: https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json
  people:
    handler: bin/people
    events:
      - httpApi:
          path: /people
          method: post
